version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 265385634200.dkr.ecr.ap-northeast-2.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building Java application...
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - echo Building the Docker image...
      - docker build -t chat-backend .
      - docker tag chat-backend:latest 265385634200.dkr.ecr.ap-northeast-2.amazonaws.com/chat-backend:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 265385634200.dkr.ecr.ap-northeast-2.amazonaws.com/chat-backend:latest
      - echo Writing image definitions file...
      - printf '[{"name":"chat-backend-container","imageUri":"265385634200.dkr.ecr.ap-northeast-2.amazonaws.com/chat-backend:latest"}]' > imagedefinitions.json
      - echo Updating task definition with image URI...
      - sed -i 's|<IMAGE1_NAME>|265385634200.dkr.ecr.ap-northeast-2.amazonaws.com/chat-backend:latest|g' task-definition.json

artifacts:
  files:
    - imagedefinitions.json
    - task-definition.json
  name: BuildOutput