server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatdb?userSSL=false
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show_sql: true


jwt:
  secretKey: y3y1y123a1231d970gh5l5678jGH6JG77JH123dklS1123DA768FF123af3123fg
  expiration: 3000